### PR TITLE
Incrimental progress update

### PR DESCRIPTION
**Pull request by AshotC**
Minor fixes
Some changes to clarify a few things
Added test cases
Added some dependency injection

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @adm27788

**Comment by kyledewey** [comment]
Additionally assigned @michaelmunje

**Review by adm27788 — APPROVED** [review]
Some of the variable names should be changed so they are not just a letter. Other than that everything looks good.

**Review by michaelmunje — APPROVED** [review]
Looks good to me.

**Pull request merged**
